FROM golang:1.12.1 as builder
WORKDIR /var/tmp
USER daemon
COPY Makefile .
COPY sleepy-c.go .
ENV GOCACHE=/var/tmp/.gocache
RUN make sleepy-c
RUN make test

FROM scratch
WORKDIR /
COPY --from=builder /var/tmp/sleepy-c .
USER 1
ENTRYPOINT ["/sleepy-c"]
