FROM golang:1.12.1 as builder
WORKDIR /var/tmp
USER daemon
COPY Makefile .
COPY sleepy.go .
ENV GOCACHE=/var/tmp/.gocache
RUN make sleepy
RUN make test

FROM busybox:1.30.1
WORKDIR /
COPY --from=builder /var/tmp/sleepy .
USER daemon
ENTRYPOINT ["/sleepy"]
